name: Build Zygisk Module

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
        
    - name: Build Module
      run: |
        export MY_NDK=${{ steps.setup-ndk.outputs.ndk-path }}
        # Link Zygisk.hpp mới chuẩn đét
        wget -qO src/zygisk.hpp https://raw.githubusercontent.com/topjohnwu/Zygisk-Module-Sample/master/module/jni/zygisk.hpp
        
        mkdir -p build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${MY_NDK}/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 ../src
        make
        cd ..
        
        # Package ZIP
        mkdir -p pkg/zygisk/arm64-v8a
        cp module/module.prop pkg/
        cp module/customize.sh pkg/
        cp build/libzygisk_loader_bypass.so pkg/zygisk/arm64-v8a/
        cd pkg
        zip -r ../Zygisk-Loader-Bypass.zip .
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Zygisk-Loader-Bypass
        path: Zygisk-Loader-Bypass.zip
